FROM phusion/baseimage:latest

MAINTAINER @adoptopenjdk

#Executor
#	Docker container using Params passed in
#	Write bash file that does the below
#		>> Provide JDK from param 
#		>> Copy JDK into docker image
#		>> Compile/Build the project using the passed in JDK
#			>> Pass in a .sh command
#		>> Run tests using the JDK
#			>> Pass in a .sh command
#
